-Kullanım Şartları<br>
<font color="red">Depo.eneskayalar.com sitesini kullanan herkes aşağıda yazılı kuralları kabul etmiş sayılır. </font><br>
Depo.eneskayalar.com sitesi yüklenen dosyalardan dolayı hiçbir şekilde hukuki ve cezai sorumluluk kabul etmez.Yüklenen dosyalar Türkiye Cumhuriyeti yasalarına, kişilik haklarına ve telif haklarına uygun olmalıdır.Aksi takdirde tüm sorumluluk dosyayı yükleyen kişiye ait olacaktır.<br>
Depo.eneskayalar.com sitesi, barındırdığı dosyaların içeriğinden ötürü doğabilecek maddi ve manevi mağduriyetlerden ve zararlardan sorumlu tutulamaz. </br>
Kullanıcı, paylaşım sistemini yasal olmayan amaçlar doğrultusunda kullanmamayı kabul eder.</br>
Telif hakkı başkasına ait olan dosyaların yüklenmesi yasaktır.</br>
Kullanıcı, Türkiye Cumhuriyeti Kanunlarına göre suç teşkil eden dosyaları yüklememeyi kabul eder.</br>
Tüm Torrent dosyaları, crack dosyaları veya bir programı / oyunu crack etmeye yarayan dosyalar, telif hakkı bulunan müzik dosyaları, telif hakları bulunan tüm TV, Film ve dizi görüntüleri barındıran multimedya içerik, yetişkin içeriği barındıran erotik veya pornografik dosyalar, içeriğinde şiddet ve aşağılama bulunan dosyalar, rahatsız edici içerik içeren dosyalar, uyuşturucu ve uyuşturucu kullanımına teşvik içeren dosyalar tespit edildiği anda veya herhangi bir şikayet üzerine sitemizden, dosyayı yükleyen kişiye haber vermeksizin silinecektir.</br>
Depo.eneskayalar.com, yüklenilen dosyaların içerikleri ile ilgili herhangi bir sorumluluk kabul etmez.Tüm sorumluluk dosyayı yükleyene aittir. Depo.eneskayalar.com sitesi, çalışanları ve yönetimi site içerisine bir yükleme yapmaz ve paylaşmaz.</br>
Depo.eneskayalar.com, hiçbir şekilde dosyalarınızı gizli yapmamaktadır. Yüklenen dosyalar, arama motorlarında çıkabilir ve herkes ulaşabilir konumdadır. Bu sebepten özel olduğunu düşündüğünüz veya gizliliği önemli olan dosyaları paylaşmamanız gerekmektedir. Aksi halde oluşabilecek zararlardan Depo.eneskayalar.com sitesi sorumluk kabul etmez. </br>
Depo.eneskayalar.com yüklenilen dosyaları virüs taramasına tabi tutmaktadır(bknz.:Virustotal.com API System (belirli bir boyutu)).Bu yüzden indirdiğiniz dosyaları virüs taramasından geçirmenizi öneririz. Aksi taktirde Depo.eneskayalar.com oluşacak olan zararlardan sorumlu tutulamaz.</br>
Depo.eneskayalar.com sitesi barındırdığı dosyaları herhangi bir gerekçe göstermeden silebilir.Herhangi bir nedenden dolayı yada şikayet üzerine dosya silinmesi durumunda kullanıcı hiçbir hak talep edemez. Aynı zamanda Depo.eneskayalar.com yönetimi uygun görmediği dosyaları silme hakkına sahiptir. Bu sebepten dolayı yükleyeceğiniz dosyaların asla asıllarını sitemizde bulunduramaz ve dosya silindiği taktirde bir hak iddaa edemezsiniz.</br>
Depo.eneskayalar.com sitesi tüm dosya yükleyen kullanıcıların ip adreslerini kayıt altına almaktadır. Hukuksal bir durum söz konusu olduğunda ve bu bilgiler ilgili kurumlar tarafından resmi yöntemlerle talep edildiğinde, Depo.eneskayalar.com yönetimi sadece yasalara uygun olduğu taktirde bu bilgileri ilgili birimlerle paylaşır.</br>
Telif haklarını / Kullanım Şartlarımızı / Kişisel Haklarınızı / Pornogrofi, diğer virüslü dosyalar ve zararlı içerik ve T.C. yasalarını ihlal ettiğini düşündüğünüz dosyaları, iletisim [@] Depo.eneskayalar.com mail adresine veya ayrıca sitemizdekiŞİKAYET bölümünden bildirebilirsiniz. Şikayet mailinize en geç üç (3) iş günü içerisinde Depo.eneskayalar.com yönetimi tarafından gerekli kontroller ardından yayından kaldırılacaktır. 
Depo.eneskayalar.com sitesi bu kuralları istediği zaman tek taraflı olarak değiştirebilir.
<B><h3>Çocuk Pornosu / İstismarı / Şiddeti - Sıfır Tolerans!</h3></b></br>
Depo.eneskayalar.com yönetimi olarak biz çocuk pornosu, çocuk istismarı, çocuklara olan şiddet içeren görüntüler, yazılar ve tüm dosyalarına kesinlikle izin vermemekle birlikte, bu tür dosya paylaşımı yapanlara karşı kesinlikle bir töleransımız bulunmuyor. Bu ve benzeri dosya yükleyen ve indiren kişilerin IP numaraları / Bilgileri ile Türkiye Cumhuriyeti ilgili birimlerine / savcılığa suç duyurusunda bulunacağımızı / dosyalar yüklenip silinse dahi sitemizde tutulan loglar sayesinde geçmişe dönük olarak, yukarıda bahsedilen ilgili birimlere suç duyurusunda bulunacağız. Eğer sitemizde benzeri bir dosya ile ilgili şikayetiniz varsa, sitemizin yukarısında bulunan "ŞİKAYET" bölümünden konuyu bize bildirebilirsiniz.
